### ISSUE TITLE
What about other libraries beside node redis

### ISSUE THREAD

**Issue by NassiHarel** [dwyl/redis-connection#33]
Such as ioredis?
What about sentinel? Redis cluster?

**Comment by nelsonic** [comment]
@NassiHarel _good question_! We are using https://www.npmjs.com/package/redis for "_historical_" reasons, not because we think it's "_better_". We have not had any "_performance_" or "_reliability_" issues (_so far_) hence we have not felt the _need_ to use any other Redis module.

Have you used one of the other node modules (_as you mentioned above_) and have you had a _specific_ metric they helped you improve? (_thanks!_)

**Comment by NassiHarel** [comment]
We are using ioredis in our projects because we need sentinel support, have you consider to add your library the option to inject the factory method for creating the redis client?

**Comment by nelsonic** [comment]
@NassiHarel `while` _we_ are not using https://redis.io/topics/sentinel in our projects _yet_... we would _absolutely_ accept a PR that allowed _others_ to use it while still maintaining _backward compatibility_ and _relative_ simplicity... 👍 
Sentinel is on the "_roadmap_" https://github.com/NodeRedis/node_redis/issues/1040 for `node_redis` but does not look like work has been _started_... 🤔 
I _suspect_ we could swap out `redis` for [`ioredis`](https://github.com/luin/ioredis) and everything would "_just work_" ... if you have time, please try it on a branch! (_you've been invited to be a contributor on the repo!_)

**Comment by NassiHarel** [comment]
Thanks, meanwhile I suggest that you add the ability to inject from outside the redis configuration and also the redis client creation function.
