### ISSUE TITLE
express-session

### ISSUE THREAD

**Issue by SupertigerDev** [dwyl/redis-connection#47]
is there anyway to use this with express-session?

**Comment by nelsonic** [comment]
@supertiger1234 _thank you_ for opening this question so that we can capture the answer and others can learn from your quest to use Redis with **`express-session`**! 🎉 
The _short answer_ is Yes! But _please_ follow the instructions / usage examples in https://github.com/tj/connect-redis and if you get "stuck" ask the lovely people in the Express.js community for assistance as session caching using Redis is a "solved" problem that _many_ people will be able to help you with. 👍 
When you get it working for your App, please share any links you find helpful so we can learn too! thanks! ✨

**Comment by SupertigerDev** [comment]
but wont using connect-redis make it so there will be more than 30 connections?

**Comment by nelsonic** [comment]
@supertiger1234 as far as we're _aware_ (_from reading the `code`_) 
https://github.com/tj/connect-redis/blob/master/lib/connect-redis.js

Do you have a system level "bottleneck" (_e.g. because your Redis-as-a-Service provider limits connections_) that means you _cannot_ have more than one connection?
That was the _reason_ we created this module but it's a _very_ specific use-case that most people don't have. Most Redis service providers allow multiple connections e.g: 
https://elements.heroku.com/addons/heroku-redis
![heroku-redis-pricing](https://user-images.githubusercontent.com/194400/53188615-abfd1a00-35fd-11e9-8621-e5d88ccbe4b5.png)

Even the _free_ version of Heroku Redis allows **20 connections** which is more than "enough" for a single node.js process. And if you are using **`express-session`** or **`connect-redis`** for that matter, it will only connect _once_ per Node.js Process not instantiate a new connection per connected user. So if you end up running a _cluster_ of Node.js processes (_e.g because your VPS has 4 cores_) if each core/process connects to Redis it's still only 4 connections.

**Comment by SupertigerDev** [comment]
Ohh right, I'm using redis lab instead of heroku. So I don't need to use redis-connection. Thanks so much for the replies!

**Comment by nelsonic** [comment]
@supertiger1234 _any_ time. Best of luck with your quest! 🚀
